services:
  - type: web
    name: afritable-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: COLLECTION_ENABLED
        value: true
      - key: COLLECTION_INTERVAL_HOURS
        value: 6
